# Generated by Django 4.0.4 on 2022-04-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginName', models.CharField(max_length=50, unique=True, verbose_name='登录账号')),
                ('password', models.CharField(max_length=128, verbose_name='登录密码')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='GradeClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeName', models.CharField(max_length=50, unique=True, verbose_name='年级名')),
                ('className', models.CharField(max_length=50, unique=True, verbose_name='级名')),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField(verbose_name='消息图标')),
                ('datetime', models.DateTimeField(verbose_name='消息时间')),
                ('memberId', models.TextField(verbose_name='消息人员ID')),
                ('memberRole', models.TextField(verbose_name='消息人员角色')),
                ('title', models.TextField(verbose_name='消息标题')),
                ('notitype', models.TextField(default='notification', verbose_name='消息类型')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectText', models.CharField(max_length=200, verbose_name='题目内容')),
                ('lesson', models.CharField(max_length=50, verbose_name='课程名')),
                ('grade', models.FloatField(verbose_name='分数')),
                ('answerText', models.CharField(max_length=200, verbose_name='答案')),
            ],
        ),
        migrations.CreateModel(
            name='UserTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginName', models.CharField(max_length=50, unique=True, verbose_name='登录账号')),
                ('password', models.CharField(max_length=128, verbose_name='登录密码')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('course', models.CharField(max_length=50, verbose_name='课程')),
                ('teacherId', models.CharField(max_length=20, unique=True, verbose_name='工号')),
            ],
        ),
        migrations.CreateModel(
            name='UserStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginName', models.CharField(max_length=50, unique=True, verbose_name='登录账号')),
                ('password', models.CharField(max_length=128, verbose_name='登录密码')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('studentId', models.CharField(max_length=20, unique=True, verbose_name='学籍号')),
                ('gradeClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.gradeclassinfo', verbose_name='班级')),
            ],
        ),
        migrations.CreateModel(
            name='studentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerText', models.TextField(verbose_name='学生答题内容')),
                ('userScore', models.FloatField(verbose_name='人工评分')),
                ('autoScore', models.FloatField(verbose_name='自动评分')),
                ('gradeClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.gradeclassinfo', verbose_name='班级')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userstudent', verbose_name='学生')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subject', verbose_name='题目')),
            ],
        ),
        migrations.AddField(
            model_name='gradeclassinfo',
            name='dili',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dili', to='user.userteacher', verbose_name='地理'),
        ),
        migrations.AddField(
            model_name='gradeclassinfo',
            name='huaxue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huaxue', to='user.userteacher', verbose_name='化学'),
        ),
        migrations.AddField(
            model_name='gradeclassinfo',
            name='lishi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lishi', to='user.userteacher', verbose_name='历史'),
        ),
        migrations.AddField(
            model_name='gradeclassinfo',
            name='shenwu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shenwu', to='user.userteacher', verbose_name='生物'),
        ),
        migrations.AddField(
            model_name='gradeclassinfo',
            name='shuxue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shuxue', to='user.userteacher', verbose_name='数学'),
        ),
        migrations.AddField(
            model_name='gradeclassinfo',
            name='teacherMain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacherMain', to='user.userteacher', verbose_name='班主任'),
        ),
        migrations.AddField(
            model_name='gradeclassinfo',
            name='waiyu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiyu', to='user.userteacher', verbose_name='外语'),
        ),
        migrations.AddField(
            model_name='gradeclassinfo',
            name='wuli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wuli', to='user.userteacher', verbose_name='物理'),
        ),
        migrations.AddField(
            model_name='gradeclassinfo',
            name='xinxijishu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xinxijishu', to='user.userteacher', verbose_name='信息技术'),
        ),
        migrations.AddField(
            model_name='gradeclassinfo',
            name='yuwen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yuwen', to='user.userteacher', verbose_name='语文'),
        ),
        migrations.AddField(
            model_name='gradeclassinfo',
            name='zhengzhi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zhengzhi', to='user.userteacher', verbose_name='政治'),
        ),
        migrations.CreateModel(
            name='Examine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='考试名称')),
                ('examId', models.CharField(max_length=50, unique=True, verbose_name='考试编号')),
                ('starDate', models.DateTimeField(auto_now_add=True, verbose_name='开始考试日期')),
                ('endDate', models.DateTimeField(auto_now_add=True, verbose_name='考试结束日期')),
                ('lesson', models.CharField(max_length=50, null=True, verbose_name='课程名')),
                ('subject', models.CharField(max_length=50, null=True, verbose_name='考试题目列表')),
                ('gradeClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.gradeclassinfo', verbose_name='班级')),
            ],
        ),
    ]
