# Generated by Django 4.0.4 on 2022-04-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_gradeclassinfo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeclassinfo',
            name='className',
            field=models.CharField(max_length=50, null=True, verbose_name='级名'),
        ),
        migrations.AlterField(
            model_name='gradeclassinfo',
            name='gradeName',
            field=models.CharField(max_length=50, null=True, verbose_name='年级名'),
        ),
    ]
